options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '--platform=linux/amd64',
      '-t',
      '${_IMAGE}',
      '.'
    ]
  timeout: '600s'  

images:
- '${_IMAGE}'
