INSERT INTO `${PROJECT_ID}.${DATASET}.strava_main` (
  activity_id,
  activity_name,
  activity_type,
  start_date_utc,
  start_date_local,
  utc_offset,
  timezone,
  distance,
  moving_time,
  elapsed_time,
  elevation_gain,
  average_speed,
  max_speed,
  average_heart_rate,
  max_heart_rate,
  has_heartrate,
  average_cadence,
  average_watts,
  max_watts,
  weighted_average_watts,
  kilojoules,
  suffer_score,
  device_name,
  gear_id,
  start_lat,
  start_lng,
  end_lat,
  end_lng,
  is_private,
  commute,
  is_manual,
  ingest_ts
)
SELECT
  SAFE_CAST(activity_id AS INT64),
  name,
  sport_type,
  SAFE_CAST(start_date_utc AS TIMESTAMP),
  SAFE_CAST(start_date_local AS TIMESTAMP),
  SAFE_CAST(utc_offset AS FLOAT64),
  timezone,
  SAFE_CAST(distance_m AS FLOAT64),
  SAFE_CAST(moving_time_s AS INT64),
  SAFE_CAST(elapsed_time_s AS INT64),
  SAFE_CAST(elevation_gain_m AS FLOAT64),
  SAFE_CAST(average_speed_kmh AS INT64),
  SAFE_CAST(max_speed_kmh AS INT64),
  CAST(SAFE_CAST(average_hr AS FLOAT64) AS INT64),
  SAFE_CAST(max_hr AS INT64),
  SAFE_CAST(has_heartrate AS BOOL),
  SAFE_CAST(average_cadence AS INT64),
  SAFE_CAST(average_watts AS INT64),
  max_watts,
  SAFE_CAST(weighted_average_watts AS INT64),
  SAFE_CAST(kilojoules AS INT64),                
  SAFE_CAST(suffer_score AS INT64),
  device_name,
  gear_id,
  SAFE_CAST(start_lat AS FLOAT64),                        
  SAFE_CAST(start_lng AS FLOAT64),                         
  SAFE_CAST(end_lat AS FLOAT64),                            
  SAFE_CAST(end_lng AS FLOAT64),
  SAFE_CAST(is_private AS BOOL),
  SAFE_CAST(is_commute AS BOOL),                            
  SAFE_CAST(is_manual AS BOOL),   
  SAFE_CAST(ingest_ts AS TIMESTAMP)
FROM `${PROJECT_ID}.${DATASET}.strava_raw_ext`
-- Only insert NEW activities that aren't already in `main` (deduplication)
WHERE SAFE_CAST(activity_id AS INT64) NOT IN (
  SELECT activity_id FROM `${PROJECT_ID}.${DATASET}.strava_main`
);