-- Athena / Trino SQL
INSERT INTO "${DATABASE}"."strava_main" (
  activity_id,
  activity_name,
  activity_type,
  start_date_utc,
  start_date_local,
  utc_offset,
  timezone,
  distance,
  moving_time,
  elapsed_time,
  elevation_gain,
  average_speed,
  max_speed,
  average_heart_rate,
  max_heart_rate,
  has_heartrate,
  average_cadence,
  average_watts,
  max_watts,
  weighted_average_watts,
  kilojoules,
  suffer_score,
  device_name,
  gear_id,
  start_lat,
  start_lng,
  end_lat,
  end_lng,
  is_private,
  commute,
  is_manual,
  ingest_ts
)
SELECT
  try_cast(activity_id AS bigint) AS activity_id,
  name AS activity_name,
  sport_type AS activity_type,
  cast(try(from_iso8601_timestamp(start_date_utc)) AS timestamp) AS start_date_utc,
  cast(try(from_iso8601_timestamp(start_date_local)) AS timestamp) AS start_date_local,
  try_cast(utc_offset AS double) AS utc_offset,
  timezone,
  try_cast(distance_m AS double) AS distance,
  try_cast(moving_time_s AS bigint) AS moving_time,
  try_cast(elapsed_time_s AS bigint) AS elapsed_time,
  try_cast(elevation_gain_m AS double) AS elevation_gain,
  try_cast(average_speed_kmh AS double) AS average_speed,
  try_cast(max_speed_kmh AS double) AS max_speed,
  cast(try_cast(average_hr AS double) AS bigint) AS average_heart_rate,
  try_cast(max_hr AS bigint) AS max_heart_rate,
  try_cast(has_heartrate AS boolean) AS has_heartrate,
  try_cast(average_cadence AS bigint) AS average_cadence,
  try_cast(average_watts AS bigint) AS average_watts,
  try_cast(max_watts AS bigint) AS max_watts,
  try_cast(weighted_average_watts AS bigint) AS weighted_average_watts,
  try_cast(kilojoules AS bigint) AS kilojoules,
  try_cast(suffer_score AS bigint) AS suffer_score,
  device_name,
  gear_id,
  try_cast(start_lat AS double) AS start_lat,
  try_cast(start_lng AS double) AS start_lng,
  try_cast(end_lat AS double) AS end_lat,
  try_cast(end_lng AS double) AS end_lng,
  try_cast(is_private AS boolean) AS is_private,
  try_cast(is_commute AS boolean) AS commute,
  try_cast(is_manual AS boolean) AS is_manual,
  coalesce(
    cast(try(from_iso8601_timestamp(ingest_ts)) AS timestamp),
    current_timestamp
  ) AS ingest_ts
FROM "${DATABASE}"."strava_raw_ext" r
WHERE NOT EXISTS (
  SELECT 1
  FROM "${DATABASE}"."strava_main" m
  WHERE m.activity_id = try_cast(r.activity_id AS bigint)
);
